"""
=================================================================
 MINE SAFETY ANALYTICS  -  DATABASE BUILDER
=================================================================
 Creates mine_safety.db (SQLite) and fills it with SYNTHETIC data
 for a fictional mixed opencast + underground coal mine.

 *** ALL DATA IS SYNTHETIC AND GENERATED BY THIS SCRIPT. ***
 *** No real mine, company, worker or accident is represented. ***
 *** Names are randomly assembled and are not real people.    ***

 Run this ONCE:   python create_database.py
 It is safe to re-run - it deletes and rebuilds the database.

 The random seed is fixed, so your numbers will match mine exactly.
=================================================================
"""

import sqlite3
import random
import os
from datetime import date, timedelta

random.seed(42)          # fixed seed = same data every time you run it

DB_NAME = "mine_safety.db"


# =================================================================
# 1. CREATE THE DATABASE FILE AND THE TABLES
# =================================================================
# sqlite3 is built into Python. There is nothing to install and no
# server to run - the whole database is one file on your laptop.

if os.path.exists(DB_NAME):
    os.remove(DB_NAME)                    # start clean every run

connection = sqlite3.connect(DB_NAME)     # creates the file
cursor = connection.cursor()              # the object we send SQL through

# --- executescript() lets us run several SQL statements at once ---
cursor.executescript("""

CREATE TABLE employees (
    emp_id           INTEGER PRIMARY KEY,
    emp_name         TEXT    NOT NULL,
    designation      TEXT    NOT NULL,
    department       TEXT    NOT NULL,
    employment_type  TEXT    NOT NULL,   -- 'Departmental' or 'Contractor'
    date_joined      TEXT    NOT NULL
);

CREATE TABLE locations (
    location_id      INTEGER PRIMARY KEY,
    location_name    TEXT    NOT NULL,
    location_type    TEXT    NOT NULL,   -- Face / Haul Road / Workshop ...
    zone             TEXT    NOT NULL    -- 'Surface' or 'Underground'
);

CREATE TABLE shifts (
    shift_id         TEXT    PRIMARY KEY,   -- 'A', 'B', 'C'
    shift_name       TEXT    NOT NULL,
    start_time       TEXT    NOT NULL,
    end_time         TEXT    NOT NULL
);

CREATE TABLE incidents (
    incident_id      INTEGER PRIMARY KEY,
    incident_date    TEXT    NOT NULL,
    shift_id         TEXT    NOT NULL,
    location_id      INTEGER NOT NULL,
    emp_id           INTEGER,             -- NULL for a near miss with nobody involved
    incident_type    TEXT    NOT NULL,
    cause_category   TEXT    NOT NULL,
    days_lost        INTEGER NOT NULL DEFAULT 0,
    description      TEXT,
    FOREIGN KEY (shift_id)    REFERENCES shifts(shift_id),
    FOREIGN KEY (location_id) REFERENCES locations(location_id),
    FOREIGN KEY (emp_id)      REFERENCES employees(emp_id)
);

-- THE MOST IMPORTANT TABLE IN THE PROJECT.
-- Without exposure hours you can count accidents but you can never
-- calculate a RATE, and a count on its own tells you nothing.
CREATE TABLE monthly_exposure (
    month            TEXT    NOT NULL,     -- 'YYYY-MM'
    employment_type  TEXT    NOT NULL,
    persons_employed INTEGER NOT NULL,
    man_hours_worked INTEGER NOT NULL,
    PRIMARY KEY (month, employment_type)
);

CREATE TABLE monthly_production (
    month            TEXT    PRIMARY KEY,
    tonnes_produced  INTEGER NOT NULL
);

""")


# =================================================================
# 2. REFERENCE DATA
# =================================================================

shifts_data = [
    ("A", "Morning", "06:00", "14:00"),
    ("B", "Afternoon", "14:00", "22:00"),
    ("C", "Night", "22:00", "06:00"),
]

locations_data = [
    (1,  "Bench-1 (OC)",          "Working Bench",   "Surface"),
    (2,  "Bench-2 (OC)",          "Working Bench",   "Surface"),
    (3,  "Main Haul Road",        "Haul Road",       "Surface"),
    (4,  "Overburden Dump Yard",  "Dump Yard",       "Surface"),
    (5,  "Heavy Vehicle Workshop","Workshop",        "Surface"),
    (6,  "Coal Handling Plant",   "Processing",      "Surface"),
    (7,  "Explosive Magazine",    "Magazine",        "Surface"),
    (8,  "Weighbridge Area",      "Support",         "Surface"),
    (9,  "UG Face-A",             "Working Face",    "Underground"),
    (10, "UG Face-B",             "Working Face",    "Underground"),
    (11, "UG Haulage Roadway",    "Haulage Roadway", "Underground"),
    (12, "UG Conveyor Gallery",   "Conveyor",        "Underground"),
]

# Standard hazard groups used when classifying mine accidents.
cause_categories = [
    "Fall of Roof / Side",
    "Haulage & Transportation Machinery",
    "Other Machinery",
    "Fall of Person",
    "Fall of Object",
    "Slip / Trip / Fall on Level",
    "Electricity",
    "Explosives & Blasting",
    "Dust / Gas / Inundation",
    "Fire",
    "Manual Handling",
]

# Which hazards realistically happen where. This is what makes the
# LOCATION JOIN produce a meaningful answer instead of random noise.
location_cause_weights = {
    1:  [("Haulage & Transportation Machinery", 3), ("Fall of Object", 3), ("Fall of Person", 2), ("Explosives & Blasting", 2), ("Other Machinery", 2), ("Slip / Trip / Fall on Level", 2)],
    2:  [("Haulage & Transportation Machinery", 3), ("Fall of Object", 3), ("Fall of Person", 2), ("Explosives & Blasting", 2), ("Other Machinery", 2), ("Slip / Trip / Fall on Level", 2)],
    3:  [("Haulage & Transportation Machinery", 8), ("Slip / Trip / Fall on Level", 1), ("Other Machinery", 1)],
    4:  [("Haulage & Transportation Machinery", 5), ("Fall of Person", 2), ("Slip / Trip / Fall on Level", 2)],
    5:  [("Other Machinery", 4), ("Manual Handling", 3), ("Slip / Trip / Fall on Level", 3), ("Fall of Object", 2), ("Electricity", 2), ("Fire", 1)],
    6:  [("Other Machinery", 4), ("Fall of Person", 2), ("Electricity", 2), ("Dust / Gas / Inundation", 2), ("Manual Handling", 2), ("Slip / Trip / Fall on Level", 2)],
    7:  [("Explosives & Blasting", 6), ("Manual Handling", 2), ("Fire", 1)],
    8:  [("Slip / Trip / Fall on Level", 3), ("Haulage & Transportation Machinery", 2), ("Manual Handling", 2)],
    9:  [("Fall of Roof / Side", 6), ("Fall of Object", 2), ("Manual Handling", 2), ("Dust / Gas / Inundation", 2), ("Other Machinery", 1)],
    10: [("Fall of Roof / Side", 6), ("Fall of Object", 2), ("Manual Handling", 2), ("Dust / Gas / Inundation", 2), ("Other Machinery", 1)],
    11: [("Haulage & Transportation Machinery", 5), ("Fall of Roof / Side", 3), ("Slip / Trip / Fall on Level", 2), ("Electricity", 1)],
    12: [("Other Machinery", 4), ("Fall of Object", 2), ("Fire", 2), ("Electricity", 2), ("Manual Handling", 2)],
}

designations = [
    ("Dumper Operator",   "Excavation"),
    ("Shovel Operator",   "Excavation"),
    ("Dozer Operator",    "Excavation"),
    ("Drill Operator",    "Excavation"),
    ("Blaster",           "Explosives"),
    ("Mining Sirdar",     "Underground"),
    ("Overman",           "Underground"),
    ("Support Man",       "Underground"),
    ("Trammer",           "Underground"),
    ("Pump Operator",     "Underground"),
    ("Electrician",       "Electrical & Mechanical"),
    ("Fitter",            "Electrical & Mechanical"),
    ("Welder",            "Electrical & Mechanical"),
    ("Belt Attendant",    "Coal Handling Plant"),
    ("Plant Operator",    "Coal Handling Plant"),
    ("Helper",            "Coal Handling Plant"),
    ("Surveyor",          "Survey"),
    ("Safety Officer",    "Safety"),
]

first_names = ["Ramesh","Suresh","Mahesh","Dinesh","Rakesh","Anil","Sunil","Vijay",
               "Ajay","Sanjay","Manoj","Rajesh","Prakash","Deepak","Ashok","Vinod",
               "Amit","Sumit","Rohit","Mohit","Kiran","Arjun","Sandeep","Pradeep",
               "Naveen","Praveen","Ganesh","Bhola","Shyam","Gopal","Lakhan","Bharat"]
last_names  = ["Kumar","Sahu","Verma","Yadav","Patel","Singh","Nayak","Behera",
               "Mishra","Tiwari","Chauhan","Rathore","Meena","Bhoi","Dewangan",
               "Netam","Kashyap","Thakur","Pandey","Sharma"]


# =================================================================
# 3. BUILD THE EMPLOYEE LIST
# =================================================================
# 450 people work at the mine, but only these 120 appear by name in
# the safety records. Real mines keep the full roster in an HR system
# and the safety register only names people actually involved.

employees_data = []
used_names = set()
emp_id = 1

while emp_id <= 120:
    name = f"{random.choice(first_names)} {random.choice(last_names)}"
    if name in used_names:
        continue                     # skip duplicates, try again
    used_names.add(name)

    designation, department = random.choice(designations)

    # Contractors are ~38% of the named workforce here.
    if random.random() < 0.38:
        employment_type = "Contractor"
    else:
        employment_type = "Departmental"

    join_year = random.randint(2008, 2025)
    join_month = random.randint(1, 12)
    join_day = random.randint(1, 28)
    date_joined = f"{join_year}-{join_month:02d}-{join_day:02d}"

    employees_data.append((emp_id, name, designation, department,
                           employment_type, date_joined))
    emp_id += 1

# Quick lookup: which employees are contractors, which are departmental
contractor_ids   = [e[0] for e in employees_data if e[4] == "Contractor"]
departmental_ids = [e[0] for e in employees_data if e[4] == "Departmental"]


# =================================================================
# 4. MONTHLY EXPOSURE AND PRODUCTION
# =================================================================
# 12 months: July 2025 to June 2026.

months = []
year, month = 2025, 7
for _ in range(12):
    months.append(f"{year}-{month:02d}")
    month += 1
    if month == 13:
        month = 1
        year += 1

exposure_data = []
production_data = []

for m in months:
    # Departmental workforce: fairly stable
    dep_persons = random.randint(275, 285)
    dep_hours   = int(dep_persons * random.uniform(185, 198))   # ~8h x ~24 days

    # Contractor workforce: fluctuates more, works longer hours
    con_persons = random.randint(160, 180)
    con_hours   = int(con_persons * random.uniform(205, 222))

    exposure_data.append((m, "Departmental", dep_persons, dep_hours))
    exposure_data.append((m, "Contractor",   con_persons, con_hours))

    # Monsoon months (Jul-Sep) produce less - normal for Indian opencast
    if m[-2:] in ("07", "08", "09"):
        tonnes = random.randint(105000, 125000)
    else:
        tonnes = random.randint(145000, 172000)
    production_data.append((m, tonnes))


# =================================================================
# 5. THE SERIOUS INCIDENTS  (hand written, not random)
# =================================================================
# These 12 lost-time incidents are placed deliberately so that the
# analysis produces a clear, defensible finding. Everything else in
# the incident table is generated randomly around them.
#
# Columns: date, shift, location_id, employment_type, type, cause,
#          days_lost, description

serious_incidents = [
    ("2025-07-18", "C", 3,  "Contractor",   "Reportable Injury",     "Haulage & Transportation Machinery", 21,  "Struck by reversing dumper while walking on haul road"),
    ("2025-08-06", "A", 9,  "Departmental", "Serious Bodily Injury", "Fall of Roof / Side",                112, "Roof fall at face; support cycle not completed"),
    ("2025-09-11", "B", 5,  "Contractor",   "Reportable Injury",     "Other Machinery",                    14,  "Hand caught in belt drive during cleaning"),
    ("2025-10-02", "C", 3,  "Contractor",   "Fatal",                 "Haulage & Transportation Machinery", 0,   "Dumper collision at haul road junction during night shift"),
    ("2025-11-20", "A", 1,  "Departmental", "Reportable Injury",     "Fall of Object",                     9,   "Struck by rock rolling from bench face"),
    ("2025-12-09", "B", 6,  "Contractor",   "Serious Bodily Injury", "Other Machinery",                    96,  "Leg injury from unguarded conveyor tail pulley"),
    ("2026-01-15", "C", 11, "Contractor",   "Reportable Injury",     "Haulage & Transportation Machinery", 18,  "Crushed foot between tub and roadway side"),
    ("2026-02-03", "A", 10, "Departmental", "Reportable Injury",     "Fall of Roof / Side",                27,  "Side fall while withdrawing supports"),
    ("2026-03-22", "B", 5,  "Departmental", "Reportable Injury",     "Fall of Person",                     11,  "Fell from dumper deck during maintenance"),
    ("2026-04-14", "C", 3,  "Contractor",   "Haulage & Transportation Machinery", "Haulage & Transportation Machinery", 0, "PLACEHOLDER"),
    ("2026-05-08", "A", 2,  "Departmental", "Reportable Injury",     "Explosives & Blasting",              7,   "Flyrock injury; clearance distance not maintained"),
    ("2026-06-19", "B", 12, "Contractor",   "Reportable Injury",     "Electricity",                        16,  "Electric shock from damaged trailing cable"),
]

# Fix the placeholder row properly (kept above so the count stays 12)
serious_incidents[9] = ("2026-04-14", "C", 3, "Contractor", "Reportable Injury",
                        "Haulage & Transportation Machinery", 24,
                        "Run over by tipper while directing reversing vehicle")


# =================================================================
# 6. GENERATE ALL INCIDENTS
# =================================================================

def pick_weighted_cause(location_id):
    """Pick a hazard category that makes sense for this location."""
    options = location_cause_weights[location_id]
    pool = []
    for cause, weight in options:
        pool.extend([cause] * weight)
    return random.choice(pool)


def random_date_in_month(month_string):
    """month_string looks like '2025-07'. Returns a random day in it."""
    y, m = int(month_string[:4]), int(month_string[5:7])
    if m == 12:
        next_month = date(y + 1, 1, 1)
    else:
        next_month = date(y, m + 1, 1)
    days_in_month = (next_month - date(y, m, 1)).days
    return f"{month_string}-{random.randint(1, days_in_month):02d}"


incidents_data = []
incident_id = 1

# --- 6a. the 12 serious ones -------------------------------------
for inc_date, shift, loc, emp_type, inc_type, cause, days, desc in serious_incidents:
    if emp_type == "Contractor":
        chosen_emp = random.choice(contractor_ids)
    else:
        chosen_emp = random.choice(departmental_ids)

    incidents_data.append((incident_id, inc_date, shift, loc, chosen_emp,
                           inc_type, cause, days, desc))
    incident_id += 1

# --- 6b. 42 first-aid cases (injury, but no days lost) -----------
minor_descriptions = [
    "Minor cut to hand, dressed at first aid station",
    "Eye irritation from dust, washed and cleared",
    "Bruised knee after slipping on wet surface",
    "Minor burn while welding",
    "Sprained wrist during manual lifting",
    "Abrasion to forearm from sharp edge",
    "Foreign body in eye removed at first aid post",
]

for _ in range(42):
    m = random.choice(months)
    loc = random.randint(1, 12)
    if random.random() < 0.42:
        chosen_emp = random.choice(contractor_ids)
    else:
        chosen_emp = random.choice(departmental_ids)

    incidents_data.append((incident_id, random_date_in_month(m),
                           random.choices(["A", "B", "C"], weights=[4, 4, 3])[0],
                           loc, chosen_emp, "First Aid",
                           pick_weighted_cause(loc), 0,
                           random.choice(minor_descriptions)))
    incident_id += 1

# --- 6c. 68 near misses (nobody hurt - but the best warning you get)
nearmiss_descriptions = [
    "Loose rock observed on bench crest before it fell",
    "Dumper brake tested weak during pre-shift check",
    "Unsupported roof span noticed and barricaded",
    "Trailing cable found damaged before energising",
    "Reversing alarm found not working on tipper",
    "Person seen walking in dumper blind spot",
    "Conveyor guard found missing during inspection",
    "Blasting shelter door found jammed before blast",
    "Water accumulation noticed in roadway",
    "Gas detector alarm during routine check, area ventilated",
]

for _ in range(68):
    m = random.choice(months)
    loc = random.randint(1, 12)
    # ~40% of near misses are reported without naming a person
    if random.random() < 0.40:
        chosen_emp = None
    elif random.random() < 0.42:
        chosen_emp = random.choice(contractor_ids)
    else:
        chosen_emp = random.choice(departmental_ids)

    incidents_data.append((incident_id, random_date_in_month(m),
                           random.choices(["A", "B", "C"], weights=[4, 4, 3])[0],
                           loc, chosen_emp, "Near Miss",
                           pick_weighted_cause(loc), 0,
                           random.choice(nearmiss_descriptions)))
    incident_id += 1


# =================================================================
# 7. WRITE EVERYTHING INTO THE DATABASE
# =================================================================
# The "?" marks are PLACEHOLDERS. Never build SQL by gluing strings
# together - placeholders are safer and handle quotes for you.

cursor.executemany("INSERT INTO shifts VALUES (?,?,?,?)", shifts_data)
cursor.executemany("INSERT INTO locations VALUES (?,?,?,?)", locations_data)
cursor.executemany("INSERT INTO employees VALUES (?,?,?,?,?,?)", employees_data)
cursor.executemany("INSERT INTO incidents VALUES (?,?,?,?,?,?,?,?,?)", incidents_data)
cursor.executemany("INSERT INTO monthly_exposure VALUES (?,?,?,?)", exposure_data)
cursor.executemany("INSERT INTO monthly_production VALUES (?,?)", production_data)

connection.commit()      # commit = actually save. Forget this and nothing is written.


# =================================================================
# 8. CONFIRM WHAT WE BUILT
# =================================================================

print("=" * 60)
print("  MINE SAFETY DATABASE CREATED  (100% SYNTHETIC DATA)")
print("=" * 60)

for table in ["employees", "locations", "shifts", "incidents",
              "monthly_exposure", "monthly_production"]:
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    count = cursor.fetchone()[0]
    print(f"  {table:<22} {count:>5} rows")

print("-" * 60)
cursor.execute("""
    SELECT incident_type, COUNT(*)
    FROM incidents
    GROUP BY incident_type
    ORDER BY COUNT(*) DESC
""")
print("  Incident profile:")
for incident_type, count in cursor.fetchall():
    print(f"    {incident_type:<26} {count:>4}")

print("=" * 60)
print(f"  Saved as: {os.path.abspath(DB_NAME)}")
print("=" * 60)

connection.close()
